export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_FAIL = 'CUSTOMER_LOGIN_FAIL'
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT'

export const CUSTOMER_REG_REQUEST = 'CUSTOMER_REG_REQUEST'
export const CUSTOMER_REG_SUCCESS = 'CUSTOMER_REG_SUCCESS'
export const CUSTOMER_REG_FAIL = 'CUSTOMER_REG_FAIL'