export const FOOD_LIST_REQUEST = 'FOOD_LIST_REQUEST';
export const FOOD_LIST_SUCCESS = 'FOOD_LIST_SUCCESS';
export const FOOD_LIST_FAIL = 'FOOD_LIST_FAIL';

export const FOOD_DETAILS_REQUEST = 'FOOD_DETAILS_REQUEST';
export const FOOD_DETAILS_SUCCESS = 'FOOD_DETAILS_SUCCESS';
export const FOOD_DETAILS_FAIL = 'FOOD_DETAILS_FAIL';

export const FOOD_DELETE_REQUEST = 'FOOD_DELETE_REQUEST';
export const FOOD_DELETE_SUCCESS = 'FOOD_DELETE_SUCCESS';
export const FOOD_DELETE_FAIL = 'FOOD_DELETE_FAIL';

export const FOOD_ADD_REQUEST = 'FOOD_ADD_REQUEST';
export const FOOD_ADD_SUCCESS = 'FOOD_ADD_SUCCESS';
export const FOOD_ADD_FAIL = 'FOOD_ADD_FAIL';

export const FOOD_EDIT_REQUEST = 'FOOD_EDIT_REQUEST';
export const FOOD_EDIT_SUCCESS = 'FOOD_EDIT_SUCCESS';
export const FOOD_EDIT_FAIL = 'FOOD_EDIT_FAIL';
export const FOOD_EDIT_RESET = 'FOOD_EDIT_RESET';
