// export const RESTAURANT_USER_REGISTER_SUCCESS = 'RESTAURANT_USER_REGISTER_SUCCESS';
// export const RESTAURANT_USER_REGISTER_FAIL = 'RESTAURANT_USER_REGISTER_FAIL';
// export const RESTAURANT_USER_LOGIN_SUCCESS = 'RESTAURANT_USER_LOGIN_SUCCESS';
// export const RESTAURANT_USER_LOGIN_FAIL = 'RESTAURANT_USER_LOGIN_FAIL';
// export const RESTAURANT_USER_LOGOUT_SUCCESS = 'RESTAURANT_USER_LOGOUT_SUCCESS';
// export const RESTAURANT_USER_LOADING = 'RESTAURANT_USER_LOADING';
// export const RESTAURANT_USER_LOADED = 'RESTAURANT_USER_LOADED';
// export const RESTAURANT_AUTH_ERROR = 'RESTAURANT_AUTH_ERROR';

export const FOOD_LIST_REQUEST = 'FOOD_LIST_REQUEST';
export const FOOD_LIST_SUCCESS = 'FOOD_LIST_SUCCESS';
export const FOOD_LIST_FAIL = 'FOOD_LIST_FAIL';

export const FOOD_DETAILS_REQUEST = 'FOOD_DETAILS_REQUEST';
export const FOOD_DETAILS_SUCCESS = 'FOOD_DETAILS_SUCCESS';
export const FOOD_DETAILS_FAIL = 'FOOD_DETAILS_FAIL';

export const FOOD_DELETE_REQUEST = 'FOOD_DELETE_REQUEST';
export const FOOD_DELETE_SUCCESS = 'FOOD_DELETE_SUCCESS';
export const FOOD_DELETE_FAIL = 'FOOD_DELETE_FAIL';

// export const GET_ERRORS = 'GET_ERRORS';
// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
