export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const CUSTOMER_ORDERS_REQUEST = 'CUSTOMER_ORDERS_REQUEST';
export const CUSTOMER_ORDERS_SUCCESS = 'CUSTOMER_ORDERS_SUCCESS';
export const CUSTOMER_ORDERS_FAIL = 'CUSTOMER_ORDERS_FAIL';

export const RESTAURANT_ORDERS_REQUEST = 'RESTAURANT_ORDERS_REQUEST';
export const RESTAURANT_ORDERS_SUCCESS = 'RESTAURANT_ORDERS_SUCCESS';
export const RESTAURANT_ORDERS_FAIL = 'RESTAURANT_ORDERS_FAIL';

export const CHANGE_ORDER_STATUS_REQUEST = 'CHANGE_ORDER_STATUS_REQUEST';
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS';
export const CHANGE_ORDER_STATUS_FAIL = 'CHANGE_ORDER_STATUS_FAIL';