export const RESTAURANT_USER_LOGIN_REQUEST = 'RESTAURANT_USER_LOGIN_REQUEST'
export const RESTAURANT_USER_LOGIN_SUCCESS = 'RESTAURANT_USER_LOGIN_SUCCESS'
export const RESTAURANT_USER_LOGIN_FAIL = 'RESTAURANT_USER_LOGIN_FAIL'
export const RESTAURANT_USER_LOGOUT = 'RESTAURANT_USER_LOGOUT'

export const RESTAURANT_USER_REG_REQUEST = 'RESTAURANT_USER_REG_REQUEST'
export const RESTAURANT_USER_REG_SUCCESS = 'RESTAURANT_USER_REG_SUCCESS'
export const RESTAURANT_USER_REG_FAIL = 'RESTAURANT_USER_REG_FAIL'