export const RESTAURANT_USER_REGISTER_SUCCESS = 'RESTAURANT_USER_REGISTER_SUCCESS';
export const RESTAURANT_USER_REGISTER_FAIL = 'RESTAURANT_USER_REGISTER_FAIL';
export const RESTAURANT_USER_LOGIN_SUCCESS = 'RESTAURANT_USER_LOGIN_SUCCESS';
export const RESTAURANT_USER_LOGIN_FAIL = 'RESTAURANT_USER_LOGIN_FAIL';
export const RESTAURANT_USER_LOGOUT_SUCCESS = 'RESTAURANT_USER_LOGOUT_SUCCESS';
export const RESTAURANT_USER_LOADING = 'RESTAURANT_USER_LOADING';
export const RESTAURANT_USER_LOADED = 'RESTAURANT_USER_LOADED';
export const RESTAURANT_AUTH_ERROR = 'RESTAURANT_AUTH_ERROR';

export const GET_FOODS = 'GET_FOODS';
export const ADD_FOOD = 'ADD_FOOD';
export const DELETE_FOOD = 'DELETE_FOOD';
export const FOODS_LOADING = 'FOODS_LOADING';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
